let
    DataMin = List.Min(fTrafego_Transacoes[Date]),
    DataMax = List.Max(fTrafego_Transacoes[Date]),
    QtdeDias = Duration.Days(DataMax - DataMin) + 1,
    ListDatas = List.Dates(DataMin, QtdeDias, #duration(1, 0, 0, 0)),
    #"Convertido para Tabela" = Table.FromList(ListDatas, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Nomear Coluna como Data" = Table.RenameColumns(#"Convertido para Tabela",{{"Column1", "Data"}}),
    #"Alterar para Tipo Data" = Table.TransformColumnTypes(#"Nomear Coluna como Data",{{"Data", type date}}),
    #"Data Resumo" = Table.AddColumn(#"Alterar para Tipo Data", "DataResumo", each Text.Combine({Date.ToText([Data], "dd"), "/", Text.Proper(Date.ToText([Data], "MMM")), Text.Middle(Date.ToText([Data], "yyyy"), 2)}), type text),
    #"Dia Inserido" = Table.AddColumn(#"Data Resumo", "Dia", each Date.Day([Data]), Int64.Type),
    #"Numero Dia da Semana" = Table.AddColumn(#"Dia Inserido", "Dia da Semana", each Date.DayOfWeek([Data]), Int64.Type),
    #"Verificar se Dia Util" = Table.AddColumn(#"Numero Dia da Semana", "Dia Útil", each if[Dia da Semana]<6 and [Dia da Semana]>0 then 1 else 0),
    #"Abrev. Nome Dia da Semana" = Table.AddColumn(#"Verificar se Dia Util", "Nome Dia da Semana", each Date.ToText([Data],"ddd")),
    #"Semana do Ano" = Table.AddColumn(#"Abrev. Nome Dia da Semana", "Semana do Ano", each Date.WeekOfYear([Data]), Int64.Type),
    #"Semana do Mês" = Table.AddColumn(#"Semana do Ano", "Semana do Mês", each Date.WeekOfMonth([Data]), Int64.Type),
    #"Mês" = Table.AddColumn(#"Semana do Mês", "Mês", each Date.Month([Data]), Int64.Type),
    #"Nome do Mês" = Table.AddColumn(#"Mês", "Nome do Mês", each Date.MonthName([Data]), type text),
    #"Inserir DiaMes" = Table.AddColumn(#"Nome do Mês", "DiaMes", each Text.Combine({Text.From([Dia], "pt-BR"), "/", Text.Start(Text.Proper([Nome do Mês]), 3)}), type text),
    #"Ano" = Table.AddColumn(#"Inserir DiaMes", "Ano", each Date.Year([Data]), Int64.Type),
    #"MesAno" = Table.AddColumn(#"Ano", "MesAno", each Text.Combine({Text.Start(Text.Proper([Nome do Mês]), 3), "/", Text.From([Ano], "pt-BR")}), type text),
    #"AnoMes" = Table.AddColumn(#"MesAno", "AnoMes", each Text.Combine({Text.From([Ano], "pt-BR"), Text.PadStart(Text.From([Mês], "pt-BR"), 2, "0")}), type text),
    #"AnoMesDia" = Table.AddColumn(#"AnoMes", "AnoMesDia", each Text.Combine({Date.ToText([Data], "yyyy"), Date.ToText([Data], "MM"), Date.ToText([Data], "dd")}), type text),
    #"MesDia" = Table.AddColumn(AnoMesDia, "MesDia", each Text.AfterDelimiter([AnoMesDia], "2", 2), type text),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"MesDia",{{"AnoMesDia", Int64.Type}}),
    #"Bimestre" = Table.AddColumn(#"Tipo Alterado", "Bimestre", each Number.RoundUp([Mês]/2)),
    #"Trimestre" = Table.AddColumn(#"Bimestre", "Trimestre", each Date.QuarterOfYear([Data]), Int64.Type),
    #"Bimestre/Ano" = Table.AddColumn(#"Trimestre", "Bimestre/Ano", each Text.Combine({Text.From([Bimestre], "pt-BR"), "/Bim ", Text.From([Ano], "pt-BR")}), type text),
    #"Trimestre/Ano" = Table.AddColumn(#"Bimestre/Ano", "Trimestre/Ano", each Text.Combine({Text.From([Trimestre], "pt-BR"), "/Trim ", Text.From([Ano], "pt-BR")}), type text),
    #"Quartil" = Table.AddColumn(#"Trimestre/Ano", "Quartil", each Text.Combine({"Q", Text.From([Trimestre], "pt-BR")}), type text),
    #"QuartilAno" = Table.AddColumn(#"Quartil", "QuartilAno", each Text.Combine({Text.From([Ano], "pt-BR"), "Q", Text.From([Trimestre], "pt-BR")}), type text)
in
    QuartilAno

  
